name: CI

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-go@v7
        with:
          go-version-file: go.mod
          cache-dependency-path: go.sum
      - run: go version
      - run: go mod verify
      - run: go vet ./...
      - run: go test -race ./... -count=1
      - run: go build -buildvcs=false -trimpath .

  vulnerability:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-go@v7
        with:
          go-version-file: go.mod
          cache-dependency-path: go.sum
      - run: go run golang.org/x/vuln/cmd/govulncheck@latest ./...
